name: Generate README from Tree

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate tree and overwrite README.md
        run: (echo '```'; tree -I 'node_modules|.git|.github'; echo '```') > README.md

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Regenerate README with directory tree"
          file_pattern: README.md
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"